"""se añade tabla usuarios y columna en conversations para login

Revision ID: 7d6e22c636b0
Revises: 
Create Date: 2026-04-16 18:14:06.339424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6e22c636b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_column('conversation', 'user_id')
    # ### end Alembic commands ###jilihuhl
